"""Initial setup

Revision ID: 89a6c6a9cef5
Revises: 
Create Date: 2024-04-21 12:36:36.881144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a6c6a9cef5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_email_key', 'customers', type_='unique')
    op.drop_index('idx_customers_email', table_name='customers')
    op.drop_index('idx_customers_name', table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index('idx_customers_name', 'customers', ['name'], unique=False)
    op.create_index('idx_customers_email', 'customers', ['email'], unique=False)
    op.create_unique_constraint('customers_email_key', 'customers', ['email'])
    # ### end Alembic commands ###
